# Generated by Django 4.0.3 on 2022-03-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.RemoveField(
            model_name='esta',
            name='id_curso',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.RemoveField(
            model_name='rinde',
            name='id_pr',
        ),
        migrations.DeleteModel(
            name='Cursos',
        ),
        migrations.DeleteModel(
            name='Esta',
        ),
        migrations.DeleteModel(
            name='Pruebas',
        ),
        migrations.DeleteModel(
            name='Rinde',
        ),
    ]
